language: rust
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
notifications:
  email: false
  slack: way-cooler:bf5hNqMVmTgFpHo3a3vgZ4Lu
script: cargo build --verbose
