[package]
name = "rustwlc"
description = "wlc Wayland library bindings for Rust"
version = "0.2.0"
repository = "https://github.com/Immington-Industries/rust-wlc/"
keywords = ["wlc", "Wayland", "compositor", "bindings"]
readme = "README.md"
license = "MIT"
authors = ["Snirk Immington <snirk.immington@gmail.com>", "Timidger <apragmaticplace@gmail.com>"]

[dependencies]
libc = "0.2.4"
bitflags = "0.4.0"
