ideal_width = 90
fn_call_width = 90
struct_lit_width = 50

fn_args_paren_newline = false

impl_empty_single_line = false

fn_args_density = "Compressed"

struct_trailing_comma = "Never"
struct_lit_trailing_comma = "Never"
enum_trailing_comma = false

report_fixme = "Always"

match_block_trailing_comma = false
match_wildcard_trailing_comma = false

write_mode = "Overwrite"
